@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDgwNzkxNTV9.thdbLHSv3gKerWPOAltk7DtCrpHrklqihatgi1crlMk

### user create (sign up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ivy",
  "email": "ivy@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ivy@example.com",
  "password": "password"
}
