@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDgwOTcyNDZ9.y4Dbq6_GsBfFwm8otnPMY5OiLjaMAp8RzvVyq_eQC-8

### user create (sign up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ivy",
  "email": "ivy@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "socks@example.com",
  "password": "password"
}

### show
GET http://localhost:3000/users.json
Authorization: Bearer {{jwt}}