@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDgwNzg5MjR9.LVPCxqCd2wNYLiZDZfvqztG91MBHYy7wK4u_xRiyxYs

### user create (sign up)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Socks",
  "email": "socks@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "socks@example.com",
  "password": "password"
}
